In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
DataSetListingPath = 'DataSets/listings.csv'
DataSetCalendarPath = 'DataSets/calendar.csv'
DataSetReviewsPath = 'DataSets/reviews.csv'

In [3]:
df_listings = pd.read_csv(DataSetListingPath)
df_calendar = pd.read_csv(DataSetCalendarPath)
df_reviews = pd.read_csv(DataSetReviewsPath)

In [4]:
df_listings.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,241032,https://www.airbnb.com/rooms/241032,20160104002432,2016-01-04,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,...,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,953595,https://www.airbnb.com/rooms/953595,20160104002432,2016-01-04,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",...,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48
2,3308979,https://www.airbnb.com/rooms/3308979,20160104002432,2016-01-04,New Modern House-Amazing water view,New modern house built in 2013. Spectacular s...,"Our house is modern, light and fresh with a wa...",New modern house built in 2013. Spectacular s...,none,Upper Queen Anne is a charming neighborhood fu...,...,10.0,f,NaN,WASHINGTON,f,strict,f,f,2,1.15
3,7421966,https://www.airbnb.com/rooms/7421966,20160104002432,2016-01-04,Queen Anne Chateau,A charming apartment that sits atop Queen Anne...,NaN,A charming apartment that sits atop Queen Anne...,none,NaN,...,NaN,f,NaN,WASHINGTON,f,flexible,f,f,1,NaN
4,278830,https://www.airbnb.com/rooms/278830,20160104002432,2016-01-04,Charming craftsman 3 bdm house,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,Cozy family craftman house in beautiful neighb...,none,We are in the beautiful neighborhood of Queen ...,...,9.0,f,NaN,WASHINGTON,f,strict,f,f,1,0.89

In [5]:
df_listings.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'summary',
       'space', 'description', 'experiences_offered', 'neighborhood_overview',
       'notes', 'transit', 'thumbnail_url', 'medium_url', 'picture_url',
       'xl_picture_url', 'host_id', 'host_url', 'host_name', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'street', 'neighbourhood', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'city', 'state', 'zipcode', 'market',
       'smart_location', 'country_code', 'country', 'latitude', 'longitude',
       'is_location_exact', 'property_type', 'room_type', 'accommodates',
       'bathrooms', 'bedrooms', 'beds', 'bed_type', 'amenities', 'square_feet',
       'price', 'weekly_price', 'monthly_price', 'security_deposit',
       'cleaning_fee', 'guests_included', 'extra_people', 'minimum_nights',
       'maximum_nights', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'first_review', 'last_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'requires_license',
       'license', 'jurisdiction_names', 'instant_bookable',
       'cancellation_policy', 'require_guest_profile_picture',
       'require_guest_phone_verification', 'calculated_host_listings_count',
       'reviews_per_month'],
      dtype='object')

In [6]:
# Check for unique values to understand some columns better
columns_to_check = ['experiences_offered','neighborhood_overview', 'transit', 'street', 'neighbourhood', 'neighbourhood_cleansed', 'city', 'state','market',
       'smart_location', 'country', 'review_scores_rating','review_scores_accuracy','jurisdiction_names']
for column in columns_to_check:
    unique_values = df_listings[column].unique()
    print(f"Unique values in '{column}': {unique_values}\n")

Unique values in 'experiences_offered': ['none']

Unique values in 'neighborhood_overview': [nan
 'Queen Anne is a wonderful, truly functional village.  You can walk everywhere... for coffee, for groceries, for a night out, for breathtaking views of the Puget Sound.'
 'Upper Queen Anne is a charming neighborhood full of a mix of beautifully maintained, turn-of-the-century craftsman homes, tudors and modern homes.  The "main drag" is Queen Anne Ave. with a great selection of boutiques, restaurants, coffee shops and bars.  Upper Queen Anne is just 1.5 miles from downtown Seattle, and situated on a hilltop with stunning panoramic views in every direction -- downtown Seattle, the Space Needle and Mt. Rainier to the southeast, Elliott Bay to the southwest, the Olympic Mountains to the west and the Cascade Mountains to the east. If you\'re a walker, you\'ll love the 4-mile "Crown of Queen Anne" loop which takes in all of these views!'
 ...
 "We're located near lots of family fun. Woodland Park Zoo is 6 block walk away (say hello to its new tigers!). For prospective students and their families, the University of Washington is only 2.5 miles from our door. And be sure to stop by the Ballard Sunday Farmers Market for fresh cut flowers, fruits and vegetables to enjoy at home! When you're ready to explore downtown Seattle, the bus is only 4 blocks away."
 'The neighborhood is a quiet oasis that is close to all the activities in Seattle.'
 'Madison Park offers a peaceful slow pace upscale Seattle vibe. You can walk to 12 different eating and drinking establishments which most include outdoor seating.  Just steps away from the newly expanded North Beach. Madison Park is centrally located, it is approximately 4 miles East of Downtown Seattle.']

Unique values in 'transit': [nan
 "Convenient bus stops are just down the block, if you're headed downtown or further afield to explore.  Zip cars are also strategically located on Queen Anne hill."
 'A bus stop is just 2 blocks away.   Easy bus access to all the sites: Lower Queen Anne, Seattle Center, The Space Needle, Experience Music Project, Chihuly Glass Museum, Pacific Science Center and more.'
 ...
 'How to Get to: UW/Husky Stadium):  10 minute drive or three block walk to catch the 31/32 bus.  Can walk to the Stadium in 30 minutes. Downtown:  Multiple bus routes within 5 blocks walking will take you to the downtown core.  Uber is $10 or so.  10 Minute drive in no traffic. Greenlake:  10 Minute walk to Upper Woodland park and 20 minutes to the beach house area.'
 "The apartment is easily accessed from I-5 North & South, as well as Hwy. 99. There are 4 first-come-first-serve parking spots in the apartment's lot. Street parking isn't too bad and should be available within a block. Please note that 2nd Ave NW that fronts the building is steep. The closest bus stops are 2 blocks away (Routes 28 & 40), The Burke Gilman trail for cycling, walking etc. is a block and a half away. Walk Score walking rating is 86. Biking 88. Public transport 59."
 'Uber and Car2go are good options in Seattle. There is a bus stop 2 blocks away that will get you to downtown in 10-15 minutes.  There is a Seattle Bike Share station 2 blocks away.']

Unique values in 'street': ['Gilman Dr W, Seattle, WA 98119, United States'
 '7th Avenue West, Seattle, WA 98119, United States'
 'West Lee Street, Seattle, WA 98119, United States' ...
 'N Bowdoin Pl, Seattle, WA 98103, United States'
 'Northwest 39th Street, Seattle, WA 98107, United States'
 'South Laurel Street, Seattle, WA 98178, United States']

Unique values in 'neighbourhood': ['Queen Anne' nan 'Ballard' 'Phinney Ridge' 'Fremont' 'Lower Queen Anne'
 'Westlake' 'Wallingford' 'Green Lake' 'Minor' 'Madrona'
 'Harrison/Denny-Blaine' 'Leschi' 'University District' 'Roosevelt'
 'Madison Park' 'Capitol Hill' 'Atlantic' 'North Beacon Hill'
 'Central Business District' 'Pike Place Market' 'Pike Market' 'Eastlake'
 'Portage Bay' 'South Lake Union' 'Magnolia' 'Belltown'
 'International District' 'Yesler Terrace' 'First Hill' 'Pioneer Square'
 'Gatewood' 'The Junction' 'Arbor Heights' 'Alki' 'North Admiral'
 'Crown Hill' 'Genesee' 'Fairmount Park' 'Interbay' 'Industrial District'
 'Holly Park' 'South Beacon Hill' 'Greenwood' 'Bitter Lake' 'Fauntleroy'
 'Mount Baker' 'Columbia City' 'Seward Park' 'Brighton' 'South Delridge'
 'Highland Park' 'High Point' 'View Ridge' 'Windermere' 'Dunlap'
 'Rainier Beach' 'North Delridge' 'Maple Leaf' 'Bryant' 'Ravenna'
 'Wedgewood' 'Riverview' 'Montlake' 'Broadway' 'Stevens' 'Victory Heights'
 'Mathews Beach' 'Cedar Park' 'Meadowbrook' 'Olympic Hills'
 'North Beach/Blue Ridge' 'Broadview' 'Haller Lake' 'Pinehurst'
 'Licton Springs' 'North College Park' 'Laurelhurst' 'Seaview'
 'Georgetown' 'South Park' 'Roxhill']

Unique values in 'neighbourhood_cleansed': ['West Queen Anne' 'Adams' 'West Woodland' 'East Queen Anne' 'Wallingford'
 'North Queen Anne' 'Green Lake' 'Westlake' 'Mann' 'Madrona'
 'University District' 'Harrison/Denny-Blaine' 'Minor' 'Leschi' 'Atlantic'
 'Pike-Market' 'Eastlake' 'South Lake Union' 'Lawton Park' 'Briarcliff'
 'Belltown' 'International District' 'Central Business District'
 'First Hill' 'Yesler Terrace' 'Pioneer Square' 'Gatewood' 'Arbor Heights'
 'Alki' 'North Admiral' 'Crown Hill' 'Fairmount Park' 'Genesee' 'Interbay'
 'Industrial District' 'Mid-Beacon Hill' 'South Beacon Hill' 'Greenwood'
 'Holly Park' 'Fauntleroy' 'North Beacon Hill' 'Mount Baker' 'Brighton'
 'South Delridge' 'View Ridge' 'Dunlap' 'Rainier Beach' 'Columbia City'
 'Seward Park' 'North Delridge' 'Maple Leaf' 'Ravenna' 'Riverview'
 'Portage Bay' 'Bryant' 'Montlake' 'Broadway' 'Loyal Heights'
 'Victory Heights' 'Matthews Beach' 'Whittier Heights' 'Meadowbrook'
 'Olympic Hills' 'Roosevelt' 'Lower Queen Anne' 'Wedgwood'
 'North Beach/Blue Ridge' 'Cedar Park' 'Bitter Lake' 'Sunset Hill'
 'Haller Lake' 'Pinehurst' 'North College Park' 'Phinney Ridge'
 'Windermere' 'Laurelhurst' 'Southeast Magnolia' 'High Point' 'Seaview'
 'Georgetown' 'South Park' 'Roxhill' 'Highland Park' 'Madison Park'
 'Stevens' 'Broadview' 'Fremont']

Unique values in 'city': ['Seattle' 'Ballard, Seattle' 'West Seattle' 'Seattle ' '西雅图'
 'Phinney Ridge Seattle' 'seattle']

Unique values in 'state': ['WA' 'wa']

Unique values in 'market': ['Seattle']

Unique values in 'smart_location': ['Seattle, WA' 'Ballard, Seattle, WA' 'West Seattle, WA' 'Seattle , WA'
 '西雅图, WA' 'Phinney Ridge Seattle, WA' 'seattle, wa']

Unique values in 'country': ['United States']

Unique values in 'review_scores_rating': [ 95.  96.  97.  nan  92.  99.  98. 100.  80.  85.  84.  88.  75.  90.
  91.  94.  93.  77.  89.  71.  82.  87.  73.  83.  86.  76.  78.  66.
  74.  60.  64.  70.  68.  72.  40.  79.  55.  20.  67.  57.  65.  53.
  81.]

Unique values in 'review_scores_accuracy': [10. nan  9.  8.  6.  7.  4.  2.]

Unique values in 'jurisdiction_names': ['WASHINGTON']

In [7]:
print(df_listings.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 92 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                3818 non-null   int64
 1   listing_url                       3818 non-null   object
 2   scrape_id                         3818 non-null   int64
 3   last_scraped                      3818 non-null   object
 4   name                              3818 non-null   object
 5   summary                           3641 non-null   object
 6   space                             3249 non-null   object
 7   description                       3818 non-null   object
 8   experiences_offered               3818 non-null   object
 9   neighborhood_overview             2786 non-null   object
 10  notes                             2212 non-null   object
 11  transit                           2884 non-null   object
 12  thumbnail_url                     3498 non-null   object
 13  medium_url                        3498 non-null   object
 14  picture_url                       3818 non-null   object
 15  xl_picture_url                    3498 non-null   object
 16  host_id                           3818 non-null   int64
 17  host_url                          3818 non-null   object
 18  host_name                         3816 non-null   object
 19  host_since                        3816 non-null   object
 20  host_location                     3810 non-null   object
 21  host_about                        2959 non-null   object
 22  host_response_time                3295 non-null   object
 23  host_response_rate                3295 non-null   object
 24  host_acceptance_rate              3045 non-null   object
 25  host_is_superhost                 3816 non-null   object
 26  host_thumbnail_url                3816 non-null   object
 27  host_picture_url                  3816 non-null   object
 28  host_neighbourhood                3518 non-null   object
 29  host_listings_count               3816 non-null   float64
 30  host_total_listings_count         3816 non-null   float64
 31  host_verifications                3816 non-null   object
 32  host_has_profile_pic              3816 non-null   object
 33  host_identity_verified            3816 non-null   object
 34  street                            3818 non-null   object
 35  neighbourhood                     3402 non-null   object
 36  neighbourhood_cleansed            3818 non-null   object
 37  neighbourhood_group_cleansed      3818 non-null   object
 38  city                              3818 non-null   object
 39  state                             3818 non-null   object
 40  zipcode                           3811 non-null   object
 41  market                            3818 non-null   object
 42  smart_location                    3818 non-null   object
 43  country_code                      3818 non-null   object
 44  country                           3818 non-null   object
 45  latitude                          3818 non-null   float64
 46  longitude                         3818 non-null   float64
 47  is_location_exact                 3818 non-null   object
 48  property_type                     3817 non-null   object
 49  room_type                         3818 non-null   object
 50  accommodates                      3818 non-null   int64
 51  bathrooms                         3802 non-null   float64
 52  bedrooms                          3812 non-null   float64
 53  beds                              3817 non-null   float64
 54  bed_type                          3818 non-null   object
 55  amenities                         3818 non-null   object
 56  square_feet                       97 non-null     float64
 57  price                             3818 non-null   object
 58  weekly_price                      2009 non-null   object
 59  monthly_price                     1517 non-null   object
 60  security_deposit                  1866 non-null   object
 61  cleaning_fee                      2788 non-null   object
 62  guests_included                   3818 non-null   int64
 63  extra_people                      3818 non-null   object
 64  minimum_nights                    3818 non-null   int64
 65  maximum_nights                    3818 non-null   int64
 66  calendar_updated                  3818 non-null   object
 67  has_availability                  3818 non-null   object
 68  availability_30                   3818 non-null   int64
 69  availability_60                   3818 non-null   int64
 70  availability_90                   3818 non-null   int64
 71  availability_365                  3818 non-null   int64
 72  calendar_last_scraped             3818 non-null   object
 73  number_of_reviews                 3818 non-null   int64
 74  first_review                      3191 non-null   object
 75  last_review                       3191 non-null   object
 76  review_scores_rating              3171 non-null   float64
 77  review_scores_accuracy            3160 non-null   float64
 78  review_scores_cleanliness         3165 non-null   float64
 79  review_scores_checkin             3160 non-null   float64
 80  review_scores_communication       3167 non-null   float64
 81  review_scores_location            3163 non-null   float64
 82  review_scores_value               3162 non-null   float64
 83  requires_license                  3818 non-null   object
 84  license                           0 non-null      float64
 85  jurisdiction_names                3818 non-null   object
 86  instant_bookable                  3818 non-null   object
 87  cancellation_policy               3818 non-null   object
 88  require_guest_profile_picture     3818 non-null   object
 89  require_guest_phone_verification  3818 non-null   object
 90  calculated_host_listings_count    3818 non-null   int64
 91  reviews_per_month                 3191 non-null   float64
dtypes: float64(17), int64(13), object(62)
memory usage: 2.7+ MB
None

In [8]:
df_listings.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,reviews_per_month
count,3.818000e+03,3.818000e+03,3.818000e+03,3816.000000,3816.000000,3818.000000,3818.000000,3818.000000,3802.000000,3812.000000,...,3171.000000,3160.000000,3165.000000,3160.000000,3167.000000,3163.000000,3162.000000,0.0,3818.000000,3191.000000
mean,5.550111e+06,2.016010e+13,1.578556e+07,7.157757,7.157757,47.628961,-122.333103,3.349398,1.259469,1.307712,...,94.539262,9.636392,9.556398,9.786709,9.809599,9.608916,9.452245,NaN,2.946307,2.078919
std,2.962660e+06,0.000000e+00,1.458382e+07,28.628149,28.628149,0.043052,0.031745,1.977599,0.590369,0.883395,...,6.606083,0.698031,0.797274,0.595499,0.568211,0.629053,0.750259,NaN,5.893029,1.822348
min,3.335000e+03,2.016010e+13,4.193000e+03,1.000000,1.000000,47.505088,-122.417219,1.000000,0.000000,0.000000,...,20.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,NaN,1.000000,0.020000
25%,3.258256e+06,2.016010e+13,3.275204e+06,1.000000,1.000000,47.609418,-122.354320,2.000000,1.000000,1.000000,...,93.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,1.000000,0.695000
50%,6.118244e+06,2.016010e+13,1.055814e+07,1.000000,1.000000,47.623601,-122.328874,3.000000,1.000000,1.000000,...,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,1.000000,1.540000
75%,8.035127e+06,2.016010e+13,2.590309e+07,3.000000,3.000000,47.662694,-122.310800,4.000000,1.000000,2.000000,...,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,2.000000,3.000000
max,1.034016e+07,2.016010e+13,5.320861e+07,502.000000,502.000000,47.733358,-122.240607,16.000000,8.000000,7.000000,...,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,37.000000,12.150000

In [9]:
df_listings.isnull().sum()

id                                    0
listing_url                           0
scrape_id                             0
last_scraped                          0
name                                  0
                                   ...
cancellation_policy                   0
require_guest_profile_picture         0
require_guest_phone_verification      0
calculated_host_listings_count        0
reviews_per_month                   627
Length: 92, dtype: int64

In [10]:
df_reviews.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,7202016,38917982,2015-07-19,28943674,Bianca,Cute and cozy place. Perfect location to every...
1,7202016,39087409,2015-07-20,32440555,Frank,Kelly has a great room in a very central locat...
2,7202016,39820030,2015-07-26,37722850,Ian,"Very spacious apartment, and in a great neighb..."
3,7202016,40813543,2015-08-02,33671805,George,Close to Seattle Center and all it has to offe...
4,7202016,41986501,2015-08-10,34959538,Ming,Kelly was a great host and very accommodating ...

In [11]:
df_reviews.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')

In [12]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84849 entries, 0 to 84848
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     84849 non-null  int64
 1   id             84849 non-null  int64
 2   date           84849 non-null  object
 3   reviewer_id    84849 non-null  int64
 4   reviewer_name  84849 non-null  object
 5   comments       84831 non-null  object
dtypes: int64(3), object(3)
memory usage: 3.9+ MB

In [13]:
df_calendar.head()

   listing_id        date available   price
0      241032  2016-01-04         t  $85.00
1      241032  2016-01-05         t  $85.00
2      241032  2016-01-06         f     NaN
3      241032  2016-01-07         f     NaN
4      241032  2016-01-08         f     NaN